# Generated by Django 6.0.7 on 2026-07-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.FloatField(blank=True, help_text='e.g. 10.7870 (right-click the spot on Google Maps to copy)', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.FloatField(blank=True, help_text='e.g. 79.1378', null=True),
        ),
    ]
