# Generated by Django 4.2.30 on 2026-08-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_age_user_bio_user_from_location_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='room_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('pg_private', 'PG - Private Room'), ('pg_shared', 'PG - Shared Room'), ('homestay_private', 'Home stay - Private Room'), ('homestay_shared', 'Home stay - Shared Room'), ('rental', 'Rental House'), ('private', 'Private Room'), ('shared', 'Shared Room'), ('guesthouse', 'Guest House'), ('full_house', 'Full Rental House')], default='hotel', max_length=30),
        ),
    ]
